In [1]:
import pandas as pd 
# suncare_top30
#긍/부/중 문장 리스트 파일 가져오기
# rc
top_rc3_positive_list_df = pd.read_excel(r"C:\Users\82108\Desktop\final\top_rc3_positive_list.xlsx")
top_rc3_negative_list_df = pd.read_excel(r"C:\Users\82108\Desktop\final\top_rc3_negative_list.xlsx")
top_rc3_neutral_list_df = pd.read_excel(r"C:\Users\82108\Desktop\final\top_rc3_neutral_list.xlsx")

## 좋X(3333)

In [2]:
top_rc3_positive_list_df

                                                    text
0                                         무난 사용 갘 아 잘 사용
1                                                     감사
2                                           샘플 챙기 주 시 감사
3                                                  진짜 필수
4                                     항상 올리브 영 제품 잘 구매 있
...                                                  ...
15926  장점 끈적이 크림 제형 젤 제형 선 젤백탁 없이 촉촉하 크림 제형 선 젤 제형 끈적...
15927  선 젤 산뜻 보습 정도 있 선 젤 여성 분 선 젤 바르 화장 밀리 현상 거의 없 피...
15928    자외선 차단 기능 서 젤 효능 효과 보 피부 미백 및 피부 주름 개선 효과 있 선 젤
15929                                           발림 잘 올라가
15930  저 서 크림 권장량 그대로 다 바르 눈 시리 있 선 크림 제품 많 이거 바르 피부 ...

[15931 rows x 1 columns]

In [3]:
from collections import Counter


# 직접적인 단어 빈도 계산
# 텍스트를 공백 기준으로 분할하여 모든 단어를 리스트로 만듦
top_rc3_positive_words = top_rc3_positive_list_df['text'].str.split().sum()
top_rc3_negative_words = top_rc3_negative_list_df['text'].str.split().sum()
top_rc3_neutral_words = top_rc3_neutral_list_df['text'].str.split().explode().tolist()
# 단어들의 빈도를 계산
top_rc3_positive_words_freq = Counter(top_rc3_positive_words)
top_rc3_negative_words_freq = Counter(top_rc3_negative_words)
top_rc3_neutral_words_freq = Counter(top_rc3_neutral_words)

# 빈도 데이터를 데이터프레임으로 변환하여 정렬
top_rc3_positive_words_freq_df = pd.DataFrame(top_rc3_positive_words_freq.items(), columns=['단어', '빈도']).sort_values(by='빈도', ascending=False).reset_index(drop=True)
top_rc3_negative_words_freq_df = pd.DataFrame(top_rc3_negative_words_freq.items(), columns=['단어', '빈도']).sort_values(by='빈도', ascending=False).reset_index(drop=True)
top_rc3_neutral_words_freq_df = pd.DataFrame(top_rc3_neutral_words_freq.items(), columns=['단어', '빈도']).sort_values(by='빈도', ascending=False).reset_index(drop=True)

# 상위 30개 단어 출력
top_rc3_positive_words_freq_df.head(30)

    단어    빈도
0    잘  9474
1    쓰  3670
2    있  3615
3   바르  3468
4   크림  2920
5   만족  2421
6   사용  2336
7    되  2207
8    같  2187
9   피부  1967
10   선  1850
11   없  1764
12  발리  1735
13  너무  1612
14   안  1473
15   보  1426
16  제품  1406
17   주  1349
18   않  1314
19  화장  1284
20  구매  1280
21   서  1173
22   사  1120
23   때  1040
24   저   965
25   톤   912
26  발림   894
27  없이   837
28   맞   780
29  친구   761

In [4]:
# rc
# 행 선택
negative_top_30 = top_rc3_negative_words_freq_df[0:30]
positive_top_30 = top_rc3_positive_words_freq_df[0:30]

# 부정 프레임과 긍정 프레임의 단어 리스트 추출
negative_words = set(negative_top_30['단어'])  
positive_words = set(positive_top_30['단어'])  

# 중복 단어만 필터링
common_words = negative_words & positive_words

common_negative_df = negative_top_30[negative_top_30['단어'].isin(common_words)]
common_positive_df = positive_top_30[positive_top_30['단어'].isin(common_words)]

# 중복 단어를 제외한 데이터프레임 필터링
filtered_negative_df = negative_top_30[~negative_top_30['단어'].isin(common_words)]
filtered_positive_df = positive_top_30[~positive_top_30['단어'].isin(common_words)]

# 결과 출력
print("두 데이터프레임에 공통으로 있는 단어:")
print(pd.concat([common_negative_df, common_positive_df], axis=1))

# print("\n중복 단어를 제외한 부정 단어 빈도:")
# print(filtered_negative_df)

# print("\n중복 단어를 제외한 긍정 단어 빈도:")
# print(filtered_positive_df)

두 데이터프레임에 공통으로 있는 단어:
     단어     빈도   단어      빈도
0    바르  920.0    잘  9474.0
1    크림  696.0    쓰  3670.0
3     있  592.0   바르  3468.0
4     없  578.0   크림  2920.0
5     쓰  502.0  NaN     NaN
6    없이  435.0   사용  2336.0
7    피부  409.0    되  2207.0
8     선  408.0    같  2187.0
9     같  337.0   피부  1967.0
10    않  331.0    선  1850.0
11   사용  318.0    없  1764.0
12   너무  308.0  NaN     NaN
14    잘  294.0    안  1473.0
15    서  291.0    보  1426.0
16   제품  265.0   제품  1406.0
17    보  256.0    주  1349.0
18    안  236.0    않  1314.0
19    때  235.0  NaN     NaN
21    되  232.0    서  1173.0
26    주  159.0  NaN     NaN
28    저  152.0  NaN     NaN
2   NaN    NaN    있  3615.0
13  NaN    NaN   너무  1612.0
23  NaN    NaN    때  1040.0
24  NaN    NaN    저   965.0
27  NaN    NaN   없이   837.0

중복 단어를 제외한 부정 단어 빈도:
    단어   빈도
2   부담  616
13  걱정  294
20   수  232
22   나  229
23  불편  188
24  힘들  166
25  수분  164
27   화  154
29  여름  148

중복 단어를 제외한 긍정 단어 빈도:
    단어    빈도
5   만족  2421
12  발리  1735
19  화장  1284
20  구매  1280
22   사  1120
25   톤   912
26  발림   894
28   맞   780
29  친구   761

In [5]:
# rc
print("\n중복 단어를 제외한 긍정 단어 빈도:")
print(filtered_positive_df)

중복 단어를 제외한 긍정 단어 빈도:
    단어    빈도
5   만족  2421
12  발리  1735
19  화장  1284
20  구매  1280
22   사  1120
25   톤   912
26  발림   894
28   맞   780
29  친구   761

In [6]:
# rc
print("\n중복 단어를 제외한 부정 단어 빈도:")
print(filtered_negative_df)

중복 단어를 제외한 부정 단어 빈도:
    단어   빈도
2   부담  616
13  걱정  294
20   수  232
22   나  229
23  불편  188
24  힘들  166
25  수분  164
27   화  154
29  여름  148